### ISSUE TITLE
What does `x-discord-union` mean?

### ISSUE THREAD

**Issue by A5rocks** [discord/discord-api-spec#10]
As title says. There's quite a few `"x-discord-union": "oneOf"` adjacent to an `anyOf`. If this is intended, could you all update the README with what this means?

**Comment by yonilerner** [comment]
We're working on documenting all these things, but since you asked, its an extension we're using to indicate that the model is represented as a Union, and is conceptually a Union, even though it needs to be specced as an `anyOf` in OpenAPI since it could be parsed as multiple things

**Comment by A5rocks** [comment]
Alright, thanks! I look forward to the documentation for the specification (heh).
