### ISSUE TITLE
Incorrect `type` for `default_member_permissions` JSON parameter when updating global application commands

### ISSUE THREAD

**Issue by A5rocks** [discord/discord-api-spec#11]
The specification says the `default_member_permissions` JSON parameter for updating global application commands is `?integer`:

https://github.com/discord/discord-api-spec/blob/25fa3568f5103ff483577ad014454c3753dc97e9/specs/openapi.json#L3354-L3361

The documentation says the same field should be a `?string`.

**Comment by mbialecka** [comment]
Our API accepts ints in string fields and strings in int fields (as long as they can be parsed as ints). This is a flag field so I think it makes sense to spec it out as an int (e.g. we can provide max value). Building a better support for flag fields in the spec is on our backlog.

**Comment by A5rocks** [comment]
... should the `"type"` maybe be `["integer", "string", "null"]` then? With a `"pattern"` to make sure the string is a number.
