### ISSUE TITLE
Meta: Possible next step of open sourcing the server itself

### ISSUE THREAD

**Issue by erkinalp** [discord/discord-api-spec#18]
Open sourcing Discord api, Discord gateway and Discord guilds server would have a huge benefit. There is a huge community that would help you fix bugs if this is seriously considered.

**Comment by broman** [comment]
Honestly erkinalp thank you for saying what everyone is too scared to say. Open-sourcing the code would not only vastly improve the experience for end-users and bot developers, by putting the code public for all to see Discord's profitability as a company would greatly improve. This is a fantastic suggestion and I can't imagine why Discord's upper management hasn't done this already.

**Comment by apacheli** [comment]
so true

**Comment by JustinBeckwith** [comment]
Greetings!  For a variety of reasons, we're not really looking to open source the entirety of the Discord backend :)
