### ISSUE TITLE
Request: Schema for the gateway payloads

### ISSUE THREAD

**Issue by danny-may** [discord/discord-api-spec#19]
Being able to use the OpenAPI spec for the REST API is great. Having something similar for the gateway would be amazing too, for example an [ASyncAPI](https://www.asyncapi.com/) spec. If thats not possible, perhaps a simple JSON schema for the messages would be useful too

**Comment by HunteRoi** [comment]
I mean it'd simplify so much!! :+1:

**Comment by yonilerner** [comment]
Thanks for the suggestion! This has been on our radar as a potential future project but is outside the scope of this repo or our current efforts.
