### ISSUE TITLE
Newest Update Doesn't Allow My IOS to Landscape Rotate.

### ISSUE THREAD

**Issue by CivilDuck** [discord/discord-api-spec#2]
so, in the recent update Discord itself and my screenshare cannot rotate into landscape mode. Every other app is able to do so except Discord. The issue may come from the fact I haven't updated my system in quite some time, but that's never been an issue before. I would love for this issue to be solved in one way or another. Thank you!

**Comment by TheKrafter** [comment]
How is this related to the discord API?

**Comment by JustinBeckwith** [comment]
Greetings!  This repository is in place specifically to manage our REST API.  For help, see https://support.discord.com/hc/en-us.
