### ISSUE TITLE
Several endpoints missing request body

### ISSUE THREAD

**Issue by danny-may** [discord/discord-api-spec#21]
Several operations are missing a request body when the docs say they support one

[`add_group_dm_user`](https://discord.com/developers/docs/resources/channel#group-dm-add-recipient-json-params) https://github.com/discord/discord-api-spec/blob/a36f8047dae17aa6f954c59b53e496b5e5773756/specs/openapi.json#L4047-L4077
[`ban_user_from_guild`](https://discord.com/developers/docs/resources/guild#create-guild-ban-json-params) https://github.com/discord/discord-api-spec/blob/a36f8047dae17aa6f954c59b53e496b5e5773756/specs/openapi.json#L7867-L7880
[`create_guild_role`](https://discord.com/developers/docs/resources/guild#create-guild-role-json-params) https://github.com/discord/discord-api-spec/blob/a36f8047dae17aa6f954c59b53e496b5e5773756/specs/openapi.json#L7683-L7703
[`prune_guild`](https://discord.com/developers/docs/resources/guild#begin-guild-prune-json-params) https://github.com/discord/discord-api-spec/blob/a36f8047dae17aa6f954c59b53e496b5e5773756/specs/openapi.json#L7799-L7819

**Comment by mbialecka** [comment]
nice catch! thank you

**Comment by mbialecka** [comment]
should be fixed now

**Comment by danny-may** [comment]
Thanks! It looks like the GET preview_prune_guild operation was given a request body now though

**Comment by JustinBeckwith** [comment]
@danny-may just to make sure we don't miss it, please open a new issue!
