### ISSUE TITLE
Bots returning "Missing Access" when trying to set voice channel status

### ISSUE THREAD

**Issue by Cynosphere** [discord/discord-api-spec#25]
Voice channel statuses have started rolling out and users seem to be able to set them fine (even outside of voice channels, which might need to be fixed), but bots just return "Missing Access".

**Comment by yonilerner** [comment]
This feature is not available for bots yet, sorry. That being said, does your bot have the right permissions for it?

**Comment by Cynosphere** [comment]
I would be getting "Missing Permissions" instead of "Missing Access" if it was permission related
