### ISSUE TITLE
Also document endpoints that only apply to human users

### ISSUE THREAD

**Issue by erkinalp** [discord/discord-api-spec#27]

**Comment by AlmostSuspense** [comment]
why are you making this issue? surely you know that the docs are only for bots, and that selfbotting isn't allowed right?

**Comment by danny-may** [comment]
Why would we need public documentation for private endpoints? Only discord is allowed to use them, why would anyone else need them documented?

**Comment by mbialecka** [comment]
Non-bot endpoints are purposefully not documented

**Comment by erkinalp** [comment]
@mbialecka Did you mean "closed as not planned"?

**Comment by erkinalp** [comment]
@danny-may to allow coordination and client interoperability with third-party server implementations
