### ISSUE TITLE
Some fields missing from UserResponse

### ISSUE THREAD

**Issue by Octol1ttle** [discord/discord-api-spec#30]
The missing fields are `global_name` (`?string`) and `avatar_decoration?` (`?string`). While present in the docs, I could not find them in either the stable or preview specs.

This also applies to `UserVIIResponse`

**Comment by mbialecka** [comment]
I've added `global_name` but I don't think we document avatar decorations anywhere. The change will be visible with the next deployment.

**Comment by Jiralite** [comment]
What about `avatar_decoration_data`? `avatar_decoration` is what is [currently documented](https://discord.com/developers/docs/resources/user#user-object-user-structure), but there is a pull request to change that: https://github.com/discord/discord-api-docs/pull/6464
