### ISSUE TITLE
Include specs for `/guilds/:id/members-search`

### ISSUE THREAD

**Issue by hackermondev** [discord/discord-api-spec#34]
The Elasticsearch member search endpoint (`/guilds/:id/members-search`) is accessible to bots and can be useful in certain situations. The old members search endpoint (`/guilds/:id/members/search`) is already documented and is in the spec but I assume this endpoint is slower and/or less accurate than the new endpoint.

This new Elasticsearch endpoint might not ever be official documented in discord/discord-api-docs but it is still useful to developers and should at least be documented in the spec. This endpoint is also the only bot-accessible endpoint right now that returns invite source data for guild members.

![image](https://github.com/discord/discord-api-spec/assets/60828015/a10ba85f-1ea3-4f5b-9ebb-dd35566515b9)
[related discussion](https://github.com/discord/discord-api-docs/discussions/3210#discussioncomment-7503972)

**Comment by yonilerner** [comment]
The spec is intended to be reflective of supported (ie. documented) API features. So this will enter the spec if/when it enters documentation

**Comment by hackermondev** [comment]
👎

**Comment by refat2090** [comment]
> @hackermondev Bots get 401Unauthorized, how did you managed to make it work?

You need to send the parameters in the body of the call.
