### ISSUE TITLE
Required properties with empty oneOfs

### ISSUE THREAD

**Issue by MoaufmKlo** [discord/discord-api-spec#36]
The [PurchaseType](https://github.com/discord/discord-api-spec/blob/5c42d970cad5a49710a2a83727d6490d826245c2/specs/openapi.json#L24017) and [SnowflakeSelectDefaultValueTypes](https://github.com/discord/discord-api-spec/blob/5c42d970cad5a49710a2a83727d6490d826245c2/specs/openapi.json#L24903) component schemas are both required properties in the components that reference them. But both of these schemas have empty oneOfs, thus not allowing for the required condition to be satisfied.

**Comment by yonilerner** [comment]
Thanks for the heads up, will fix this soon

**Comment by yonilerner** [comment]
These are fixed now
